# LABEL file 
# Last modified by ThundluckS on 13 Dec'19
# revise name for labels : 'totoro' && 'nekobus'

item {
    id: 1
    name:'fat'
}

item {
    id: 2
    name: 'sugar'
}

item {
    id: 3
    name:'salt'
}

item {
    id: 4
    name:'green'
}